baseurl = "https://laurabarrera11.github.io"
languageCode = "en-us"
title = "Laura Barrera Forero"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Laura Barrera"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "logo.png"


	# Navigation
	[params.navigation]
		brand = "Laura Barrera Forero"

		[params.navigation.links]
			about     = "About"
			portfolio = "Portfolio"
			contact   = "Contact"
			#home  = "Home"




	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Hi, I'm Laura!"
		subtitle   = "I'm a third year student at Northwestern University majoring in Computer Science in the McCormick School of Engineering and pursuing a Business Minor."
		buttonText = "About Me"


	# About section
	[params.about]
		headline    = "Some more detalis about me!"
		description = "I was born and raised in Colombia. Even though I attended one of the best schools in the country it wasn't international and didn't offer IB/AP classes. Nevertheless, I studied ahead, prepared myself for the SATs and went through college apps without much help from my school.
		I was accepted as part of Northwestern Class 2019 as a Mechanical Engineer, however, I fell in love with CS after my first year at college.I believe technology can have a positive impact on everyone around it and want to work towards making that a reality. I'm passionate about coding, technology and using it to help close digital bridges like the one in my country.During summer 2016, I interned at Nearpod and worked on the UX/UI side of their blog to increase users' knowledge of the product. I also managed team of content creators to create flagship assets used for their new product integration with Microsoft. This past summer I participated in Summer Wildfire, a startup accelerator at Northwestern University. I was part of HotPlate as a software developer and worked on the backend aspects of their React Native app."
		#buttonText  = "How do I do that?"


	# Service section
	[params.services]
		headline = "Involvement on campus"

        [[params.services.list]]
            #icon = "fa-diamond"
            title = "WiC"
            description = "I'm the treasure for Women In Computing"

        [[params.services.list]]
			#icon = "fa-paper-plane"
			title = "Pi Beta Phi"
			description = "I'm the Vice President of Finance for my sorority."

		[[params.services.list]]
            #icon = "fa-newspaper-o"
            title = "HotPlate"
            description = "I'm part of a startup as software developer."

        [[params.services.list]]
            #icon = "linkedin"
            title = "Potato"
            description = "I'm also part of this startup as UI/UX Lead."


    # Portfolio modals
	[params.portfolio.modal]
	client = "Client"
	date = "Date"
	category = "Category"
	#buttonText = "Close"

	# Aside section
	[params.aside]


	[params.aside.button]
		text = "my resume"
		link = "https://drive.google.com/file/d/0B5LHCkdgI_gpLUhHU3ZqOURjU0k/view?usp=sharing"


	# Contact section
	[params.contact]
		headline = "Contact me"
		description = "Now that you know me a little bit better, I would love to hear from you! Feel free say hi!"
		email="laurabarrera2019@u.northwestern.edu"
		github="GitHub"
		LinkedInID="LinkedIn"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
